# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "WindowsVistaSP2_x86_S"
  config.ssh.insert_key = false
  config.vm.guest = :windows

  # ssh access with publickey or password 
  # config.ssh.username = "IEUser"

  # ssh access with password
  # config.ssh.password = "Passw0rd!"

  # winrm access
  config.vm.communicator = "winrm"
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"
  config.winrm.max_tries = 20
  config.vm.network :forwarded_port, guest: 3389, host: 33389, auto_correct: true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  # config.vm.synced_folder "b:/", "c:/Projects"

  config.vm.provider "virtualbox" do |vb|
    # vb.name = "Windows Vista SP2 x86"

    vb.gui = true
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    # vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
    vb.customize ["modifyvm", :id, "--vram", "132"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    # vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "hyperv"]
    vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--audio", "dsound"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  # config.vm.define :windows_vista_sp2_x86 do |t|
  # end

  # provision with winrm powershell
  config.vm.provision "shell", path: 'provisions/provision_install_soft.ps1'

  # provision with ssh shell
  # config.vm.provision "shell", privileged: false, path: 'provisions/provision_install_soft.sh'


end
