# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "Windows7_SP1_x86"
  config.ssh.insert_key = false
  config.vm.guest = :windows

  # config.ssh.username = "IEUser"
  # config.ssh.password = "Passw0rd!"

  config.vm.communicator = "winrm"
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"
  config.winrm.max_tries = 20
  config.vm.network :forwarded_port, guest: 3389, host: 33389, auto_correct: true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  config.vm.synced_folder "b:/", "c:/Projects"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Windows 7 SP1 x86"

    vb.gui = true
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    # vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
    vb.customize ["modifyvm", :id, "--vram", "132"]
    # vb.customize ["modifyvm", :id, "--ioapic", "on"]
    # vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    # vb.customize ["modifyvm", :id, "--paravirtprovider", "hyperv"]
    vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--audio", "dsound"]
  end

  # config.vm.define :windows_vista_sp2_x86 do |t|
  # end

  # config.vm.provision "shell", path: 'provisions/provision_install_soft.ps1'
  config.vm.provision "shell", privileged: false, path: 'provisions/provision_install_soft.sh'

end
